### ISSUE TITLE
Make images in the slider clickable

### ISSUE THREAD

**Issue by s-canchi** [ThibaultJanBeyer/carousel-slider.js#3]
I have an implementation of the carousel-slider which was really easy to use and is well made. I would like to implement the ability of the user to click on the image in the slideshow and link it to a relevant page within the website structure. I tried using the anchor tags for the individual image deck but that did not help.

**Comment by ThibaultJanBeyer** [comment]
Hi @s-canchi and thanks for using the slider. That should work out of the box, you can just use normal HTML within the slider, nothing special. Can you maybe share a code pen? So we can see whether it's an issue in the slider?
I'll close it for now, if it's really an issue in the slider, we can re-open-
Thank you :)
